# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: example.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'example.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexample.proto\x12\nexample.v1\"\x1e\n\x0e\x45xampleRequest\x12\x0c\n\x04word\x18\x01 \x01(\t\"&\n\x0f\x45xampleResponse\x12\x13\n\x0btranslation\x18\x01 \x01(\t2V\n\x0e\x45xampleService\x12\x44\n\x07\x45xample\x12\x1a.example.v1.ExampleRequest\x1a\x1b.example.v1.ExampleResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXAMPLEREQUEST']._serialized_start=29
  _globals['_EXAMPLEREQUEST']._serialized_end=59
  _globals['_EXAMPLERESPONSE']._serialized_start=61
  _globals['_EXAMPLERESPONSE']._serialized_end=99
  _globals['_EXAMPLESERVICE']._serialized_start=101
  _globals['_EXAMPLESERVICE']._serialized_end=187
# @@protoc_insertion_point(module_scope)
